fitchecks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [


    path('admin/', admin.site.urls),
    path('users/', include('users.urls'),),
    path('', include('fits.urls')),

]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fits/urls.py
from django.urls import path
from . import views

app_name = 'fits'
urlpatterns = [
    path('', views.index, name='index'),
    path('feed', views.feed, name="feed"),
    path('all', views.all, name="all"),
    path('like', views.like, name='like_fit'),
    path('fun', views.fun, name="fun"),
    path('<owner>/liked_fits', views.liked_fits, name='liked_fits'),
    path('<owner>/new_fit', views.new_fit, name='new_fit'),
    path('<owner>/closets', views.closets, name='closets'),
    path('<owner>', views.closets, name="closets"),
    path('<owner>/closets/new_closet', views.new_closet, name='new_closet'),
    path('<owner>/<shown_id>', views.fit, name='fit'),
    path('<owner>/closets/<style>/delete', views.delete_closet, name='delete_closet'),
    path('<owner>/closets/<style>', views.closet, name='single_closet'),
    path('<owner>/<shown_id>/delete', views.delete_fit, name='delete_fit'),
    path('<owner>/<shown_id>/edit_fit', views.edit_fit, name='edit_fit'),
    path('<owner>/<shown_id>/edit_fit_elements', views.edit_fit_elements, name='edit_fit_elements'),
    path('<owner>/<shown_id>/add_fit_elements', views.add_fit_elements, name='add_fit_elements'),
    path('<owner>/closets/<style>/remove', views.remove_fits, name='remove_fits'),
    path('<owner>/closets/<style>/add', views.add_fits, name="add_fits"),
    path('<owner>/closets/<style>/edit', views.edit_closet, name='edit_closet'),






]

users/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('login', auth_views.LoginView.as_view(template_name="registration/login.html",
                                               redirect_authenticated_user=True), name='login'),
    path('register', views.register, name='register'),
    path('<owner>/edit_profile', views.edit_profile, name='edit_profile'),
    path('<owner>/delete_profile', views.delete_profile, name='delete_profile')
]

fits/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image, ExifTags
import uuid
from djmoney.models.fields import MoneyField


class Closet(models.Model):
    style = models.CharField(max_length=50, default="main_closet")
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)
    private = models.BooleanField(default=False)

    class Meta:
        unique_together = ["owner", "style"]

    def __str__(self):
        if " " in self.style:
            return "".join(self.style)
        return self.style


class Fit(models.Model):
    """An Outfit"""
    description = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='images/')
    tags = models.CharField(max_length=100, blank=True)
    closet = models.ManyToManyField(Closet)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    shown_id = models.CharField(max_length=32, primary_key=False, default=uuid.uuid4, editable=False,
                                unique=True)
    private = models.BooleanField(default=False)

    class Meta:
        unique_together = ["shown_id", "owner", "image", "description"]

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None, *args, **kwargs):
        # saving image first
        super(Fit, self).save(*args, **kwargs)

        img = Image.open(self.image.path)  # Open image using self
        try:

            for orientation in ExifTags.TAGS.keys():
                if ExifTags.TAGS[orientation] == 'Orientation':
                    break

            exif = img._getexif()

            if exif[orientation] == 3:
                img = img.rotate(180, expand=True)
            elif exif[orientation] == 6:
                img = img.rotate(270, expand=True)
            elif exif[orientation] == 8:
                img = img.rotate(90, expand=True)


        except (AttributeError, KeyError, IndexError):
            # cases: image don't have getexif
            pass

        if img.height > 500 or img.width > 500:
            new_img = (500, 500)
            img.thumbnail(new_img)
            img.save(self.image.path, quality=100)

    def __str__(self):
        return self.description[:10]


class Top(models.Model):
    brand = models.CharField(max_length=30, blank=True)
    size = models.CharField(max_length=15, blank=True)
    color = models.CharField(max_length=20, blank=True)
    description = models.CharField(max_length=50)
    price = MoneyField(max_digits=14, decimal_places=2, blank=True, null=True)
    fit = models.ForeignKey(Fit, on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        unique_together = ["brand", "description", "color", "price", "fit"]

    def __str__(self):
        return self.description[:10]


class Bottom(models.Model):
    brand = models.CharField(max_length=30, blank=True)
    size = models.CharField(max_length=15, blank=True)
    color = models.CharField(max_length=20, blank=True)
    description = models.CharField(max_length=50)
    price = MoneyField(max_digits=14, decimal_places=2, blank=True, null=True)
    fit = models.ForeignKey(Fit, on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        unique_together = ["brand", "description", "color", "price", "fit"]

    def __str__(self):
        return self.description[:10]


class Accessory(models.Model):
    brand = models.CharField(max_length=30, blank=True)
    size = models.CharField(max_length=15, blank=True)
    color = models.CharField(max_length=20, blank=True)
    description = models.CharField(max_length=50)
    price = MoneyField(max_digits=14, decimal_places=2, blank=True, null=True)
    fit = models.ForeignKey(Fit, on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        unique_together = ["brand", "description", "color", "price", "fit"]

    def __str__(self):
        return self.description[:10]


class Shoe(models.Model):
    brand = models.CharField(max_length=30, blank=True)
    size = models.CharField(max_length=15, blank=True)
    color = models.CharField(max_length=20, blank=True)
    description = models.CharField(max_length=50)
    price = MoneyField(max_digits=14, decimal_places=2, blank=True, null=True)
    fit = models.ForeignKey(Fit, on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        unique_together = ["brand", "description", "color", "price", "fit"]

    def __str__(self):
        return self.description[:10]


class Comment(models.Model):
    fit = models.ForeignKey(Fit, related_name='details', on_delete=models.CASCADE)
    username = models.ForeignKey(User, related_name='details', on_delete=models.CASCADE)
    comment = models.CharField(max_length=255)
    comment_date = models.DateTimeField(auto_now_add=True)


class Like(models.Model):
    user = models.ForeignKey(User, related_name='likes', on_delete=models.CASCADE)
    fit = models.ForeignKey(Fit, related_name='likes', on_delete=models.CASCADE)
    like_date = models.DateTimeField(auto_now_add=True)

fits/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Closet, Fit, Top, Accessory, Bottom, Shoe, Like
from users.models import Profile
from .forms import ClosetForm, FitForm, TopForm, AccessoryForm, ShoeForm, BottomForm, AccessoryFormSet, CommentForm, \
    LikedFitsForm
from django.contrib.auth.models import User
from django.http import Http404, HttpResponse
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
import json
from django.core.exceptions import ObjectDoesNotExist


def index(request):
    if request.user.is_authenticated:
        return redirect("fits:feed")

    return render(request, 'fits/index.html')


def feed(request):
    context = {}
    following = []
    followed_people = request.user.profile.following.all()
    fits = Fit.objects.filter(owner__profile__in=followed_people, private=False) | \
           Fit.objects.filter(owner__username=request.user).order_by("-date_added")

    context.update({'fits': fits})

    if not request.user.is_authenticated:
        return redirect("fits:all")

    else:
        liked = [i for i in Fit.objects.all() if Like.objects.filter(user=request.user, fit=i)]
        context['liked_post'] = liked
        for fit in fits:
            curr_user = request.user.profile
            followee = Profile.objects.get(user__username=fit.owner)
            follower = followee.followers.all()
            if curr_user in follower:
                following.append(fit)
    context["following_user"] = following

    page = request.GET.get('page', 1)
    paginator = Paginator(fits, 8)
    try:
        fitz = paginator.page(page)
    except PageNotAnInteger:
        fitz = paginator.page(1)
    except EmptyPage:
        fitz = paginator.page(paginator.num_pages)
    context.update({"fitz": fitz, 'num_pages': paginator.num_pages})

    return render(request, 'fits/feed.html', context)


def all(request):
    fits = Fit.objects.filter(private=False).order_by("-date_added")
    context = {'fits': fits}
    following = []

    if request.user.is_authenticated:
        liked = [i for i in Fit.objects.all() if Like.objects.filter(user=request.user, fit=i)]
        context['liked_post'] = liked

        for fit in fits:
            curr_user = request.user.profile
            followee = Profile.objects.get(user__username=fit.owner)
            follower = followee.followers.all()
            if curr_user in follower:
                following.append(fit)
    context["following_user"] = following

    page = request.GET.get('page', 1)
    paginator = Paginator(fits, 8)
    try:
        fitz = paginator.page(page)
    except PageNotAnInteger:
        fitz = paginator.page(1)
    except EmptyPage:
        fitz = paginator.page(paginator.num_pages)
    context.update({"fitz": fitz,
                    "num_pages": paginator.num_pages})

    return render(request, 'fits/feed.html', context)


def closets(request, owner):
    if owner == str(request.user):
        closets = Closet.objects.filter(owner__username=owner).order_by('-date_added')
        same = True
    else:
        closets = Closet.objects.filter(owner__username=owner, private=False).order_by('-date_added')
        same = False
    context = {}
    is_following = False

    if request.user.is_authenticated:
        curr_user = request.user.profile
        followee = Profile.objects.get(user__username=owner)
        follower = followee.followers.all()
        if curr_user in follower:
            is_following = True

    owner = get_object_or_404(User, username=owner)
    context.update({'closets': closets,
                    'owner': owner,
                    "is_following": is_following,
                    "same": same}
                   )

    liked_fits = Closet.objects.get(style="liked_fits", owner__username=owner)
    main_closet = Closet.objects.get(style="main_closet", owner__username=owner)

    return render(request, "fits/closets.html", context)


def closet(request, style, owner):
    closet = Closet.objects.get(style=style, owner__username=owner)
    if closet.style == "liked_fits":
        return redirect("fits:liked_fits", owner)

    same = True
    if owner == str(request.user):
        fits = closet.fit_set.order_by('-date_added')
    else:
        if closet.private:
            raise Http404
        same = False
        fits = closet.fit_set.filter(private=False).order_by('-date_added')

    owner = get_object_or_404(User, username=owner)

    context = {
        'closet': closet,
        'fits': fits,
        'owner': owner,
        'same': same
    }

    if request.user.is_authenticated:
        liked = [i for i in Fit.objects.all() if Like.objects.filter(user=request.user, fit=i)]
        context['liked_post'] = liked

    page = request.GET.get('page', 1)
    paginator = Paginator(fits, 8)
    try:
        fitz = paginator.page(page)
    except PageNotAnInteger:
        fitz = paginator.page(1)
    except EmptyPage:
        fitz = paginator.page(paginator.num_pages)
    context.update({"fitz": fitz, 'num_pages': paginator.num_pages})

    return render(request, 'fits/single_closet.html', context)


def fit(request, owner, shown_id):
    context = {}
    fit = Fit.objects.get(shown_id=shown_id, owner__username=owner)
    if request.user.is_authenticated:
        liked = [i for i in Fit.objects.all() if Like.objects.filter(user=request.user, fit=i)]
        context['liked_post'] = liked

    try:
        bottom = fit.bottom_set.all()[0]
    except IndexError:
        pass
    else:
        context.update({"bottom": bottom})

    try:
        shoe = fit.shoe_set.all()[0]
    except IndexError:
        pass
    else:
        context.update({"shoe": shoe})

    same = True
    if owner != str(request.user):
        if fit.private:
            raise Http404
        same = False
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            data = form.save(commit=False)
            data.fit = fit
            data.username = request.user
            data.save()
            return redirect('fits:fit', owner=fit.owner, shown_id=shown_id)
    else:
        form = CommentForm()

    owner = get_object_or_404(User, username=owner)
    context.update({
        'fit': fit,
        'owner': owner,
        'same': same,
        'form': form,
    })
    return render(request, 'fits/fit.html', context)


@login_required
def new_closet(request, owner):
    """Create new closet"""
    if owner != str(request.user):
        raise Http404
    if request.method != 'POST':
        form = ClosetForm()
    else:
        form = ClosetForm(data=request.POST)
        if form.is_valid():
            new_closet = form.save(commit=False)
            new_closet.owner = request.user
            new_closet.save()
            return redirect('fits:closets', owner=new_closet.owner)

    context = {'form': form,
               'owner': owner}
    return render(request, 'fits/new_closet.html', context)


@login_required
def new_fit(request, owner):
    """Create new Outfit"""

    if owner != str(request.user):
        raise Http404

    context = {'owner': owner, }
    if request.method != 'POST':
        form = FitForm()
        top_form = TopForm()
        bottom_form = BottomForm()
        accessory_form = AccessoryForm()
        shoe_form = ShoeForm()
        context.update({"form": form,
                        'top_form': top_form,
                        "bottom_form": bottom_form,
                        "accessory_form": accessory_form,
                        'shoe_form': shoe_form})
        request.session['top_count'] = 0
        request.session['shoe_count'] = 0
        request.session['bottom_count'] = 0
        request.session['accessory_count'] = 0

    if request.method == "POST" and "new_top" in request.POST:

        top_form = TopForm(data=request.POST)
        if top_form.is_valid() and request.is_ajax():
            request.session['top_count'] += 1
            request.session[f'top_form_{request.session[f"top_count"]}'] = top_form.cleaned_data

    if request.method == "POST" and "new_bottom" in request.POST:

        bottom_form = BottomForm(data=request.POST)
        if bottom_form.is_valid() and request.is_ajax():
            request.session["bottom_count"] += 1
            request.session['bottom_form'] = bottom_form.cleaned_data

    if request.method == "POST" and "new_shoe" in request.POST:

        shoe_form = ShoeForm(data=request.POST)
        if shoe_form.is_valid() and request.is_ajax():
            request.session["shoe_count"] += 1
            request.session['shoe_form'] = shoe_form.cleaned_data

    if request.method == "POST" and "new_accessory" in request.POST:

        accessory_form = AccessoryForm(data=request.POST)
        if accessory_form.is_valid() and request.is_ajax():
            request.session["accessory_count"] += 1
            request.session[f'accessory_form_{request.session[f"accessory_count"]}'] = accessory_form.cleaned_data

    if request.method == "POST" and "add_fit" in request.POST:

        form = FitForm(request.POST, request.FILES)

        if form.is_valid():
            new_fit = form.save(commit=False)
            main_closet = Closet.objects.get(style__exact="main_closet", owner__username=owner)
            main_closet.save()

            new_fit.owner = request.user
            new_fit.save()

            if request.session['top_count'] > 0:
                for i in range(1, request.session['top_count'] + 1):
                    top = Top.objects.create(**request.session[f'top_form_{i}'])
                    new_fit.top_set.add(top)
            if request.session['bottom_count'] > 0:
                bottom = Bottom.objects.create(**request.session['bottom_form'])
                new_fit.bottom_set.add(bottom)
            if request.session['shoe_count'] > 0:

templates/fits/base.html
{% load bootstrap4 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,
        shrink-to-fit=no">
    <title>Fitchecks</title>


    {% bootstrap_css %}
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">

    {% bootstrap_javascript jquery="full" %}


</head>

<!-- #fffdfb-->
<body style="font-family: 'PT Sans', 'Helvetica', sans-serif;
        background-image:url('/media/images/white_wall_hash.png');
        background-repeat:repeat-y;
        background-size:100%;">
<nav class="navbar navbar-expand-md navbar-light py-3" style="background-color: #557A95">


    <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarCollapse">

        <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" style="color: whitesmoke" href="{% url 'fits:closets' user %}">
                        {{ user.username }}
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" style="color: whitesmoke" href="{% url 'fits:index' %}">
                        Your Feed </a></li>


                <li class="nav-item">
                    <a class="nav-link" style="color: whitesmoke"
                       href="{% url 'fits:single_closet' user 'main_closet' %}">Your Fits</a>
                </li>
            {% else %}
                <li class="nav-item">
                <a class="nav-link" href="{% url 'fits:all' %}" style="color: whitesmoke;">
                    Explore
                </a>
            {% endif %}
        </ul>

        <ul class="navbar-nav m-lg-auto">
            {% if user.is_authenticated %}
                <a class="navbar-brand px-3" style="color: whitesmoke; background-color: black;
        box-shadow: rgba(0, 0, 0, 0.3) 0 19px 38px, rgba(0, 0, 0, 0.22) 0 15px 12px;" href="{% url 'fits:all' %}">
                    FitChecks</a>
            {% else %}
                <a class="navbar-brand px-3" style="color: whitesmoke; background-color: black;
        box-shadow: rgba(0, 0, 0, 0.3) 0 19px 38px, rgba(0, 0, 0, 0.22) 0 15px 12px;" href="{% url 'fits:index' %}">
                    FitChecks</a>
            {% endif %}

        </ul>

        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" style="color: whitesmoke" href="{% url 'fits:new_closet' user %}">
                        New Closet
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" style="color: whitesmoke" href="{% url 'fits:new_fit' user %}">
                        New Fit
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" style="color: whitesmoke" href="{% url 'users:logout' %}">Log out</a>
                </li>


            {% else %}
                <li class="nav-item">
                    <a class="nav-link" style="color: whitesmoke" href="{% url 'users:register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" style=" color: whitesmoke;" href="{% url 'users:login' %}">Log in</a></li>
            {% endif %}
        </ul>


    </div>


</nav>


<main role="main" class="container-xxl mt-5" style="max-width: 1300px; margin: 0 auto; ">
    {% block page_header %}{% endblock page_header %}

    <div style="margin: 0 auto">
        {% block content %}{% endblock content %}
        <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/shortcuts/infinite.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>
        <script src="https://unpkg.com/infinite-scroll@4/dist/infinite-scroll.pkgd.min.js"></script>

        {% block javascript %}{% endblock %}
        {% block jsfiles %}{% endblock jsfiles %}
    </div>
</main>
</body>

</html>

templates/fits/delete_closet.html
<div class='col-sm-6 col-sm-offset-3'>
        <p>Are you sure you want to delete {{ closet.style }}</p>
        <form action="" method="POST">
            {% csrf_token %}
            <input type="submit" value="Delete" />
            <input type="button" value="Cancel" onclick="window.location='{% url 'fits:single_closet' closet.owner closet.style %}'"/>
        </form>
</div>

templates/fits/edit_closet.html
{% extends 'fits/base.html' %}
{% block content %}
    <p><a href="{% url 'fits:single_closet' closet.owner closet.style %}">{{ closet }}</a> </p>

    <p>Edit Closet</p>
    <form action="{% url 'fits:edit_closet' closet.owner closet.style %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Save changes</button>
     </form>

{% endblock content %}

templates/fits/fit.html
{% extends 'fits/base.html' %}
{% load static %}

{% block cssfiles %}
{% endblock cssfiles %}
{% block content %}
    <p><a class="btn follow_button" href="{% url 'fits:closets' fit.owner %}">{{ fit.owner }}</a> </p>
    <img
                src="{{ fit.image.url }}" alt="img"
            >
            <p>
                {{ fit.description }}
            </p>
            <p>
                {{ fit.tags }}
            </p>
            <p>
                {{ fit.date_added|date:'M d, Y' }}
            </p>
    <ul>
                {% for top in fit.top_set.all %}
                    <li><p>Top</p>
                    {% if top.description %}
                        <p>Description: {{ top.description }}</p>
                    {% endif %}
                    {% if top.price %}
                        <p>Price: {{ top.price }}</p>
                    {% endif %}
                    {% if top.brand %}
                        <p>Brand: {{ top.brand }}</p>
                    {% endif %}
                    {% if top.size %}
                        <p>Size: {{ top.size }}</p>
                    {% endif %}
                    {% if top.color %}
                        <p>Color: {{ top.color }}</p>
                    {% endif %}
                    </li>
                {% endfor %}
            </ul>


            {% if bottom %}
            <p>Bottom</p>
            {% endif %}
            {% if bottom.description %}
            <p>{{ bottom.description }}</p>
            {% endif %}
                {% if bottom.price %}
            <p>{{ bottom.price }}</p>
                {% endif %}
            {% if bottom.brand %}
            <p>{{ bottom.brand }}</p>
                {% endif %}
                {% if bottom.size %}
            <p>{{ bottom.size }}</p>
                {% endif %}
            {% if bottom.color %}
            <p>{{ bottom.color }}</p>
                {% endif %}


            {% if shoe %}
            <p>Shoe</p>
            {% endif %}
            {% if shoe.description %}
            <p>{{ shoe.description }}</p>
            {% endif %}
                {% if shoe.price %}
            <p>{{ shoe.price }}</p>
                {% endif %}
            {% if shoe.brand %}
            <p>{{ shoe.brand }}</p>
                {% endif %}
                {% if shoe.size %}
            <p>{{ shoe.size }}</p>
                {% endif %}
            {% if shoe.color %}
            <p>{{ shoe.color }}</p>
                {% endif %}

            <ul>
                {% for accessory in fit.accessory_set.all %}
                    <li><p>Accessory</p>
                    {% if accessory.description %}
                        <p>Description: {{ accessory.description }}</p>
                    {% endif %}
                    {% if accessory.price %}
                        <p>Price: {{ accessory.price }}</p>
                    {% endif %}
                    {% if accessory.brand %}
                        <p>Brand: {{ accessory.brand }}</p>
                    {% endif %}
                    {% if accessory.size %}
                        <p>Size: {{ accessory.size }}</p>
                    {% endif %}
                    {% if accessory.color %}
                        <p>Color: {{ accessory.color }}</p>
                    {% endif %}
                    </li>
                {% endfor %}
            </ul>
    <div class="card-footer">
        <button class="btn btn-white mr-3 like" id="{{ fit.id }}">
			        {% if fit in liked_post %}
			            <a href="{% url 'fits:like_fit' %}" style="color:red;" id="likebtn{{ fit.id }}"> Unlike</a> |


			        {% else %}
			            <a href="{% url 'fits:like_fit' %}" style="color:green;" id="likebtn{{ fit.id }}"> Like</a> |



			        {% endif %}
                    <div class="like-count{{ fit.id }}">
                {{fit.likes.count}}</div>


			    </button>
        </div>
        <h4>Comments</h4>
    <div class="row">
	    	<div class="col-md-8">
	    		{% if fit.details.all %}
	    		<div class="card card-signin my-5">
	    		{% for detail in fit.details.all %}
	    			<div class="card-body">
	    				<a href="{% url 'fits:closets' detail.username %}">
	    					<img src="/{{ detail.username.profile.get_profile_pic_url}}" class="rounded-circle" width="30" height="30" alt="">
	    				</a>
	          			<a class="text-dark" href="{% url 'fits:closets' detail.username %}"><b>{{ detail.username }}</b></a>
	          			<br><small>{{ detail.comment_date }}</small><br>
	          			<p class="card-text text-dark">{{ detail.comment }}</p>
	    			</div>
	    		{% endfor %}
	    		</div>
	    		{% else %}
	    			<p>No comments to show!</p>
	    		{% endif %}
	    	</div>

            <form action = "" method = "post">
                {% csrf_token %}
                    {{ form.as_p }}
                <div>
                    <button class="btn btn-lg btn-primary btn-block text-uppercase" name="submit">Comment</button><br>
                </div>
            </form>


    </div>


    {% if same %}
        <button type="button">
        <a href="{% url 'fits:delete_fit' fit.owner fit.shown_id %}">Delete Fit</a>
        </button>
        <button type="button">
        <a href="{% url 'fits:edit_fit' fit.owner fit.shown_id %}">Edit Fit</a>
        </button>
        <button type="button">
        <a href="{% url 'fits:edit_fit_elements' fit.owner fit.shown_id %}">Edit/Delete Elements</a>
        </button>
        <button type="button">
        <a href="{% url 'fits:add_fit_elements' fit.owner fit.shown_id %}">Add Elements</a>
        </button>
    {% endif %}
{% endblock content %}


{% block jsfiles %}
<script>
    $(document).ready(function() {
        $(".like").click(function (e) {

            var id = this.id;
            var href = $(".like").find("a").attr("href");
            var count = parseInt($('.like-count' + id).text());

            e.preventDefault();


            $.ajax({
                url: href,
                data: {
                    "likeId": id,
                },
                success: function (response) {
                    if (response.liked) {
                        $('.like-count' + id).text(count+1);
                        $("#likebtn" + id).html("Unlike");
                        $("#likebtn" + id).css("color", "red");




                    } else {
                        $('.like-count' + id).text(count-1);
                        $("#likebtn" + id).html("Like");
                        $("#likebtn" + id).css("color", "green");


                    }

                },
            });
        });
    });
</script>
{% endblock jsfiles %}

templates/fits/new_closet.html
{% extends 'fits/base.html' %}

{% block content %}
    <p>New Closet: </p>

    <form action="{% url 'fits:new_closet' owner %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Add Closet</button>
    </form>
{% endblock content %}